# Generated by Django 5.2.15 on 2026-07-04 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('short_bio', models.TextField(blank=True, help_text='Отображается во всплывающем окне на графе', max_length=500, verbose_name='Краткая информация')),
                ('full_bio', models.TextField(blank=True, verbose_name='Полное описание')),
                ('graph_x', models.FloatField(default=0, verbose_name='Позиция X на графе')),
                ('graph_y', models.FloatField(default=0, verbose_name='Позиция Y на графе')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Наши корни', max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(default='Семья — это не просто слово. Это связь поколений, история, которую мы несём в себе, и корни, которые дают нам силу двигаться вперёд. Каждый человек в этом графе — часть нашей общей истории.', verbose_name='Текст')),
                ('button_text', models.CharField(default='Открыть граф', max_length=50, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Приветственный экран',
                'verbose_name_plural': 'Приветственный экран',
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relations', to='family.person', verbose_name='Ребёнок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relations', to='family.person', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Связь родитель — ребёнок',
                'verbose_name_plural': 'Связи родитель — ребёнок',
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='SiblingRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('brother_brother', 'Брат — брат'), ('sister_sister', 'Сестра — сестра'), ('brother_sister', 'Брат — сестра')], default='brother_sister', max_length=20, verbose_name='Тип связи')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations_a', to='family.person', verbose_name='Человек A')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sibling_relations_b', to='family.person', verbose_name='Человек B')),
            ],
            options={
                'verbose_name': 'Связь братьев/сестёр',
                'verbose_name_plural': 'Связи братьев/сестёр',
                'unique_together': {('person_a', 'person_b')},
            },
        ),
    ]
