# Generated by Django 5.2.15 on 2026-08-03 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpouseRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations_a', to='family.person', verbose_name='Супруг(а) A')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spouse_relations_b', to='family.person', verbose_name='Супруг(а) B')),
            ],
            options={
                'verbose_name': 'Связь супругов',
                'verbose_name_plural': 'Связи супругов',
                'unique_together': {('person_a', 'person_b')},
            },
        ),
    ]
