# Generated by Django 5.2.15 on 2026-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_person_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_year_only',
            field=models.BooleanField(default=False, help_text='Если отмечено, на сайте покажется только год (например, 1936), без дня и месяца.', verbose_name='Известен только год рождения'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_year_only',
            field=models.BooleanField(default=False, help_text='Если отмечено, на сайте покажется только год смерти.', verbose_name='Известен только год смерти'),
        ),
    ]
