# Generated by Django 5.2.15 on 2026-08-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0004_date_year_only_flags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, help_text='Можно оставить пустым, если имя неизвестно.', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, help_text='Можно оставить пустым, если фамилия неизвестна.', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Можно оставить пустым, если отчество неизвестно.', max_length=100, verbose_name='Отчество'),
        ),
    ]
