# Generated by Django 5.2.15 on 2026-08-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_optional_name_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birth_unknown',
            field=models.BooleanField(default=False, help_text='Если отмечено, на сайте будет показано, что дата рождения неизвестна.', verbose_name='Дата рождения неизвестна'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_unknown',
            field=models.BooleanField(default=False, help_text='Если отмечено, на сайте будет показано, что дата смерти неизвестна.', verbose_name='Дата смерти неизвестна'),
        ),
    ]
